name: hack2025_mobile_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.11.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1

  flutter_tts: ^3.8.0

  # OAuth & Social Login
  kakao_flutter_sdk: ^1.9.5
  flutter_naver_login: ^1.8.0

  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0

  # State Management & Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
